version: '3.7'

services:

  calendar:
    container_name: calendar
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/diary'
      - '/diary/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true